### PR TITLE
fix regex too complicated error in developer edition

### PR DESCRIPTION
**Pull request by exiahuang**
### What does this PR do?

Fix `Regex too complicated` error in developer edition

### What issues does this PR fix or reference?

#312 

## The PR fulfills these requirements:

[x] Tests for the proposed changes have been added/updated.
[x] Code linting and formatting was performed.

### Functionality Before

Regex too complicated Error.

### Functionality After

Fix the error in DE.

### CODE REVIEW

**Comment by codefriar** [comment]
@exiahuang  - Thanks for this PR. Your solution is elegant and I like the guard/continue pattern.

It does not, however, follow our style conventions in this Repo. Can you please tweak to include {}'s around the continue statement. I know it's not *technically* required by Apex, but it is how the rest of the Repo is done.

**Comment by exiahuang** [comment]
@codefriar Thank you for for comment. I have fix it. Please check it again.

**Review by codefriar — APPROVED** [review]
@pozil I approve this PR

**Review by msrivastav13 — APPROVED** [review]

**Comment by msrivastav13** [comment]
Thank you @codefriar and @exiahuang

**Pull request merged**
