### PR TITLE
Add all classes to UI tree list

### PR DESCRIPTION
**Pull request by gusgunn**
### What does this PR do?
adds @group references to classes where there are none

### What issues does this PR fix or reference?
All classes not showing in tree list in UI

#<https://github.com/trailheadapps/apex-recipes/issues/104>

[ N/A] Tests for the proposed changes have been added/updated.
[ X] Code linting and formatting was performed.

### Functionality Before

classes not showing in UI

### Functionality After

Classes showing in UI as per folders

### CODE REVIEW

**Comment by codefriar** [comment]
@gusgunn Could you please edit your pr to enable us to make changes to this PR. That will allow our CI to work properly. More information here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by gusgunn** [comment]
Yes, sorry about that

**Comment by codefriar** [comment]
@gusgunn - just wanted to follow up with you about this. We've discovered that Github Actions isn't actually allowing us to run CI on forks, even if we have write permission to them. Our previous CI system did, and we're working out what the best path forward, long term is. In the mean time, It's entirely likely that for this PR, i'm going to pull your changes, and push to a branch owned by me in order to pull them in.

**Comment by gusgunn** [comment]
no worries here. Hope it wasn't more trouble than value added. In that
vein, I've been doing a codelive o rama and have the URL's of the sessions
to match the recipes. Some are run ons's or not labeled. If you want me to
add those links to the docs let me know where/etc specs. Thanks again for
the repo.

**Comment by codefriar** [comment]
Changed merged in #109

**Pull request closed without merging**
