### PR TITLE
Update case to match declarations in many files

### PR DESCRIPTION
**Pull request by codefriar**
See Aidan Harding's PR

### CODE REVIEW

**Comment by codefriar** [comment]
Aidan Harding's PR is #69

**Review by msrivastav13 — APPROVED** [review]

**Comment by msrivastav13** [comment]
@aidan-harding Thanks for the contribution!

Since apex is not case-sensitive IMHO naming conventions are personal preferences as long as one adopts one and sticks with it.

I liked what you did there to make it consistent!

**Comment by aidan-harding** [comment]
Thanks @msrivastav13 - These mismatches count as warnings in Illuminated Cloud - justifiably so, in my opinion because consistency helps the reader.

Since it's a push-button fix, it seemed like a good first bug before taking a closer look at the rest of this repo. It already started a debate in our team on WITH SECURITY_ENFORCED and stripInnacessible()

**Review by pozil — APPROVED** [review]
+1 to that PR for the sake of consistency. This rule also applies to the other sample apps.

**Pull request merged**
