### PR TITLE
Update capitalisation to match declarations in many files

### PR DESCRIPTION
**Pull request by aidan-harding**
e.g. boolean => Boolean, exception => Exception

### What does this PR do?

Fixed many code-inspection warnings where the Apex is legal, but the capitalisation doesn't match between declaration and use

### What issues does this PR fix or reference?

No issue listed, just a simple fix

## The PR fulfills these requirements:

[ ] Tests for the proposed changes have been added/updated.
[ ] Code linting and formatting was performed.

No functional change, but ran all Apex tests and they still pass. No formatting change. The fix is a linting fix. 

### Functionality Before

N/A

### Functionality After

N/A

### CODE REVIEW

**Comment by aidan-harding** [comment]
Hi @codefriar 

I started looking at the Apex Recipes in earnest, and I thought I'd contribute by doing some housekeeping before looking at anything more substantial. 

Unfortunately, this seems to have coincided with a CLI issue (https://github.com/forcedotcom/cli/issues/811) which meant that my PR failed to pass CI tests. 

Now, I'm not sure what happens next. I've not used Github actions like this, so I don't know if there's something I can do to rerun the tests, or the next step is for a manual review when you or one of the other owners can take a look.

Help!

**Comment by codefriar** [comment]
@aidan-harding  - Thanks for this! I'm working through it right now

**Comment by codefriar** [comment]
@aidan-harding due to the way our CI is setup, I'm going to have to manually pull your branch into one I control. That's going to functionally look like me closing this PR, but please be aware, your work is being incorporated!

**Comment by aidan-harding** [comment]
No problem - thanks for your time!

**Pull request closed without merging**
